spring:
  datasource:
    url: jdbc:mariadb://localhost:4417/zoo?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: zoo
    password: zoo
    driver-class-name:  org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true

  thymeleaf:
    cache: false
#      spring.thymeleaf.mode=LEGACYHTML5
#      spring.thymeleaf.prefix=/templates/

logging:
  level:
    org:
      springframework:
        messaging: DEBUG